// Encodes reference/*.md into refs-data.js as window.STUDIO_REFS.
// Run once after editing any reference doc:  node build-refs.mjs
import { readFileSync, writeFileSync, readdirSync } from "node:fs";
import { join } from "node:path";

const dir = join(import.meta.dirname, "reference");
const files = readdirSync(dir).filter((f) => f.endsWith(".md"));

const refs = {};
for (const f of files) {
  const id = f.replace(/\.md$/, "");
  refs[id] = readFileSync(join(dir, f), "utf8");
}

const out = `// AUTO-GENERATED by build-refs.mjs — do not edit by hand.
window.STUDIO_REFS = ${JSON.stringify(refs, null, 2)};
`;
writeFileSync(join(import.meta.dirname, "refs-data.js"), out, "utf8");
console.log(
  "Wrote refs-data.js with",
  Object.keys(refs).length,
  "reference docs:",
  Object.keys(refs).join(", "),
);
