// Ambient types for the document model that data.js and refs-data.js publish on
// `window`. The three data files are plain scripts loaded by <script src>, so
// there is nothing to import — this file is what lets `tsc --noEmit` check them
// and app.js against one shared shape instead of against `any`.

/** A blank in the document. `computed` fields are derived, never typed into. */
interface StudioField {
  id: string;
  group: string;
  label: string;
  type: "text" | "date" | "select" | "computed";
  value?: string;
  placeholder?: string;
  hint?: string;
  /** Present on `select`: the combobox suggestion list. */
  options?: string[];
  /** Present on `computed`: the field ids this value is derived from. */
  derivedFrom?: string[];
}

/** An authority cited by the document. */
interface StudioCitation {
  id: string;
  kind: "case" | "statute" | "rule";
  short: string;
  full: string;
  authority: string;
  /**
   * Precedential weight as shown on the badge. app.js matches /binding/i then
   * /controlling/i and falls through to persuasive, so a qualifier such as
   * "Controlling (state law)" is meaningful text rather than a fourth value.
   */
  weight:
    | "Binding"
    | "Controlling"
    | "Controlling (state law)"
    | "Persuasive"
    | "Persuasive (state law)";
  proposition: string;
  /** Id of the research memo this authority was drawn from. */
  source?: string;
  url?: string;
}

/** One research memo, as listed in the Sources tab. */
interface StudioRefMeta {
  id: string;
  title: string;
  blurb: string;
}

/** One block of the document. `html` carries {{FIELD}} and [[CITE]] markers. */
interface StudioSection {
  id: string;
  kind:
    | "court"
    | "parties"
    | "title"
    | "h1"
    | "h2"
    | "h3"
    | "body"
    | "signature"
    | "certificate";
  part: string;
  html: string;
  citations?: string[];
  references?: string[];
  derivation?: string;
}

declare global {
  interface Window {
    STUDIO_FIELDS: StudioField[];
    STUDIO_CITATIONS: StudioCitation[];
    STUDIO_REF_META: StudioRefMeta[];
    STUDIO_DOC: StudioSection[];
    /** Generated by build-refs.ts: memo id -> markdown body. */
    STUDIO_REFS: Record<string, string>;
    /**
     * Test hook published by app.js at the end of `init`, so a browser test can
     * drive the studio without synthesising clicks. Nothing in the shipped
     * interface reads it.
     */
    __recital: {
      state: {
        values: Record<string, string>;
        edits: Record<string, string>;
        mode: "fill" | "edit" | "read";
        tab: "context" | "authorities" | "sources";
        selected: string | null;
        sourceFilter: string | null;
      };
      setTab: (
        tab: "context" | "authorities" | "sources",
        flashId?: string,
      ) => void;
      selectSection: (id: string) => void;
      locateCitation: (id: string, scroll?: boolean) => void;
    };
  }
}

export {};
